version: "3.8"
services:
  db:
    container_name: postgres-db
    hostname: postgres
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"

  be:
    container_name: be
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "3333:8000"
    restart: always
